#pragma once

#include "Windows.h"

#define NUM_BACKBUFFERS 3
#define NUM_SCENE_DOWNSAMPLES 6
#define NUM_BLOOM_TARGETS NUM_SCENE_DOWNSAMPLES * 2

#define BLOOM_STATIC_SAMPLE_COUNT 7
#define BLOOM_PACKED_SAMPLE_COUNT ( BLOOM_STATIC_SAMPLE_COUNT + 1 ) / 2

#define DISPLAY_OUTPUT_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM
#define DEPTH_FORMAT DXGI_FORMAT_D32_FLOAT
#define DEPTH_STENCIL_FORMAT DXGI_FORMAT_D24_UNORM_S8_UINT

#define GBUFFER_GUID_FORMAT DXGI_FORMAT_R32G32B32A32_UINT

#define GBUFFER_COLOR_DEFERRED_FORMAT DXGI_FORMAT_R16G16B16A16_FLOAT
#define GBUFFER_BASE_COLOR_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM_SRGB
#define GBUFFER_MASKS_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM
#define GBUFFER_VELOCITY_FORMAT DXGI_FORMAT_R16G16_UNORM
#define GBUFFER_WORLD_NORMAL_FORMAT DXGI_FORMAT_R16G16_FLOAT

#define DECAL_BASE_COLOR_FORMAT GBUFFER_BASE_COLOR_FORMAT
#define DECAL_MASKS_FORMAT GBUFFER_MASKS_FORMAT
#define DECAL_NORMAL_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM

#define SCENE_DOWN_SAMPLE_FORMAT DXGI_FORMAT_R11G11B10_FLOAT
#define BLOOM_FORMAT SCENE_DOWN_SAMPLE_FORMAT

#define EDITOR_PRIMITIVE_COLOR_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM_SRGB


#define D3D12_RESOURCE_STATE_TBD D3D12_RESOURCE_STATES(-1 ^ (1 << 31))
#define D3D12_RESOURCE_STATE_CORRUPT D3D12_RESOURCE_STATES(-2 ^ (1 << 31))

#define VERIFYD3D12RESULT(x)			{HRESULT hres = x; if (FAILED(hres)) { VerifyD3D12Result(hres, #x, __FILE__, __LINE__); }}

void SetName(class ID3D12Object* const Object, const std::string& Name);
//void SetName(class Drn::RenderResource* const Resource, const std::string& Name);